[project]
name = "paradise-kiss-api"
version = "0.1.0"
description = "Django REST API for Paradise Kiss"
requires-python = ">=3.12"
dependencies = [
  "Django==6.1.1",
  "djangorestframework==3.18.1",
  "google-genai==2.28.0",
  "django-cors-headers==4.9.0",
  "dj-database-url==3.1.2",
  "gunicorn==26.2.0",
  "psycopg[binary]==3.3.6",
  "python-dotenv==1.2.3",
]

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["backend*", "resources*"]

[tool.vercel]
entrypoint = "backend.wsgi:application"
