# Generated by Django 6.1.1 on 2026-09-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resources_email_resources_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='resources',
            name='manufacurer',
        ),
        migrations.AddField(
            model_name='resources',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.category'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.gender'),
        ),
        migrations.AddField(
            model_name='resources',
            name='manufacturer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='resources.manufacturer'),
            preserve_default=False,
        ),
    ]
