# Generated by Django 6.1.1 on 2026-10-05 06:35

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


CATEGORY_PROFILES = (
    ('Tees', 95, Decimal('28.00')),
    ('Hoodies', 72, Decimal('65.00')),
    ('Jeans', 65, Decimal('78.00')),
    ('Tops', 84, Decimal('42.00')),
    ('Jackets', 58, Decimal('120.00')),
    ('Dresses', 69, Decimal('95.00')),
    ('Skirts', 55, Decimal('58.00')),
    ('Shirts', 62, Decimal('55.00')),
    ('Knitwear', 48, Decimal('75.00')),
    ('Shorts', 60, Decimal('45.00')),
)

YEAR_FACTORS = {
    2023: Decimal('0.84'),
    2024: Decimal('0.96'),
    2025: Decimal('1.10'),
}

QUARTER_FACTORS = {
    1: Decimal('0.86'),
    2: Decimal('1.03'),
    3: Decimal('0.94'),
    4: Decimal('1.17'),
}


def seed_sales_data(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    Category = apps.get_model('resources', 'Category')
    SalesData = apps.get_model('resources', 'SalesData')
    sales_rows = []

    for category_index, (category_name, base_units, average_price) in enumerate(CATEGORY_PROFILES):
        category, _ = Category.objects.get_or_create(name=category_name)
        category_factor = Decimal('0.97') + Decimal(category_index % 4) * Decimal('0.02')

        for year, year_factor in YEAR_FACTORS.items():
            for quarter, quarter_factor in QUARTER_FACTORS.items():
                units_sold = int(
                    Decimal(base_units) * year_factor * quarter_factor * category_factor
                )
                sales_rows.append(
                    SalesData(
                        year=year,
                        quarter=quarter,
                        category=category,
                        units_sold=units_sold,
                        revenue=Decimal(units_sold) * average_price,
                    )
                )

    SalesData.objects.bulk_create(sales_rows, ignore_conflicts=True)


def secure_sales_table(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('alter table public.resources_salesdata enable row level security;')
        cursor.execute(
            'revoke all privileges on table public.resources_salesdata from anon, authenticated;'
        )
        cursor.execute(
            'revoke all privileges on sequence public.resources_salesdata_id_seq '
            'from anon, authenticated;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_category_gender_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField()),
                ('units_sold', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_data', to='resources.category')),
            ],
            options={
                'ordering': ['year', 'quarter', 'category__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quarter__gte', 1), ('quarter__lte', 4)), name='sales_quarter_between_1_and_4'), models.UniqueConstraint(fields=('year', 'quarter', 'category'), name='unique_sales_period_category')],
            },
        ),
        migrations.RunPython(seed_sales_data, migrations.RunPython.noop),
        migrations.RunPython(secure_sales_table, migrations.RunPython.noop),
    ]
