# Generated by Django 6.1.1 on 2026-10-05 08:00

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def secure_inventory_sale_table(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('alter table public.resources_inventorysale enable row level security;')
        cursor.execute(
            'revoke all privileges on table public.resources_inventorysale '
            'from anon, authenticated;'
        )
        cursor.execute(
            'revoke all privileges on sequence public.resources_inventorysale_id_seq '
            'from anon, authenticated;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_salesdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('sold_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sales', to='resources.resources')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_sale_quantity_positive'), models.CheckConstraint(condition=models.Q(('stock_before__gte', models.F('quantity'))), name='inventory_sale_stock_sufficient'), models.CheckConstraint(condition=models.Q(('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '-', models.F('quantity')))), name='inventory_sale_stock_consistent')],
            },
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(
                condition=models.Q(('amount__gte', 0)),
                name='resource_amount_non_negative',
            ),
        ),
        migrations.RunPython(secure_inventory_sale_table, migrations.RunPython.noop),
    ]
