# Generated by Django 6.1.1 on 2026-10-05 09:35

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def backfill_sale_movements(apps, schema_editor):
    InventorySale = apps.get_model('resources', 'InventorySale')
    StockMovement = apps.get_model('resources', 'StockMovement')

    for sale in InventorySale.objects.all().iterator():
        movement = StockMovement.objects.create(
            resource_id=sale.resource_id,
            resource_name=sale.resource_name,
            movement_type='sale',
            quantity=sale.quantity,
            stock_before=sale.stock_before,
            stock_after=sale.stock_after,
            performed_by_id=sale.sold_by_id,
        )
        StockMovement.objects.filter(pk=movement.pk).update(occurred_at=sale.sold_at)


def secure_stock_movement_table(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('alter table public.resources_stockmovement enable row level security;')
        cursor.execute(
            'revoke all privileges on table public.resources_stockmovement '
            'from anon, authenticated;'
        )
        cursor.execute(
            'revoke all privileges on sequence public.resources_stockmovement_id_seq '
            'from anon, authenticated;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_inventorysale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='bin_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='resources',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='resources',
            name='shelf_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('movement_type', models.CharField(choices=[('sale', 'Verkauf'), ('restock', 'Nachbestellung')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='resources.resources')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['movement_type', '-occurred_at'], name='movement_type_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'sale'), ('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '-', models.F('quantity')))), models.Q(('movement_type', 'restock'), ('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '+', models.F('quantity')))), _connector='OR'), name='stock_movement_amount_consistent')],
            },
        ),
        migrations.RunPython(backfill_sale_movements, migrations.RunPython.noop),
        migrations.RunPython(secure_stock_movement_table, migrations.RunPython.noop),
    ]
