# Generated by Django 6.1.1 on 2026-10-05 13:32

from django.db import migrations, models

from resources.gtin import build_gtin


def assign_missing_gtins(apps, schema_editor):
    Resource = apps.get_model('resources', 'resources')
    database = schema_editor.connection.alias
    for resource in Resource.objects.using(database).filter(gtin__isnull=True).only('pk'):
        resource.gtin = build_gtin(resource.pk)
        resource.save(using=database, update_fields=['gtin'])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_add_stock_location_and_movements'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='gtin',
            field=models.CharField(blank=True, editable=False, help_text='Globale Artikelnummer (GTIN-13), wird beim Speichern automatisch vergeben.', max_length=13, null=True, unique=True, verbose_name='GTIN'),
        ),
        migrations.RunPython(assign_missing_gtins, migrations.RunPython.noop),
    ]
