# Generated by Django 6.1.1 on 2026-10-05 17:41

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_require_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='stock_movement_amount_consistent',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Verkauf'), ('restock', 'Nachbestellung'), ('cancellation', 'Storno')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'sale'), ('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '-', models.F('quantity')))), models.Q(('movement_type__in', ['restock', 'cancellation']), ('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '+', models.F('quantity')))), _connector='OR'), name='stock_movement_amount_consistent'),
        ),
    ]
