# Generated by Django 6.1.1 on 2026-10-05 18:00

from django.db import migrations, models


def backfill_unit_prices(apps, schema_editor):
    """Sales registered before prices existed get the product's current RT price."""
    InventorySale = apps.get_model('resources', 'InventorySale')
    database = schema_editor.connection.alias
    sales = (
        InventorySale.objects.using(database)
        .filter(unit_price__isnull=True, resource__isnull=False)
        .select_related('resource')
    )
    for sale in sales:
        sale.unit_price = sale.resource.retail_price
        sale.save(using=database, update_fields=['unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_stock_movement_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysale',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RT-Preis pro Stück zum Zeitpunkt des Verkaufs.', max_digits=10, null=True, verbose_name='Verkaufspreis'),
        ),
        migrations.RunPython(backfill_unit_prices, migrations.RunPython.noop),
    ]
